(define (domain gripper)
	(:requirements :typing)
	(:types 
		 location gripper object
	)
	(:predicates
		(atrob ?loc - location)
		(spare-in ?loc - location)
		(adj ?from - location ?to - location)
		(room ?r - location)
		(ball ?o - object)
		(gripper ?gr - gripper)
		(at ?o - object ?r - location)
		(free ?gr - gripper)
		(carry ?o - object ?gr - gripper)
		(scratch)
		(turndomain)
		(q1 ?loc68 - location ?o87 - object)
		(q2 ?loc68 - location ?o87 - object)
	)
	(:action move 
		:parameters (?from - location ?to - location)
		:precondition (and  (atrob ?from) (adj ?from ?to) (room ?from) (turndomain))
		:effect (oneof (d2 (and (not (atrob ?from)) (atrob ?to) (not (turndomain))))
		 (d1 (and (not (atrob ?from)) (atrob ?to) (scratch) (not (turndomain))))
		)
	)
	(:action pick 
		:parameters (?b - object ?r - location ?g - gripper)
		:precondition (and  (atrob ?r) (ball ?b) (gripper ?g) (at ?b ?r) (free ?g) (turndomain))
		:effect (oneof (d2 (and (carry ?b ?g) (not (at ?b ?r)) (not (free ?g)) (not (turndomain))))
		 (d1 (and (at ?b ?r) (free ?g) (not (carry ?b ?g)) (not (turndomain))))
		)
	)
	(:action drop 
		:parameters (?b - object ?r - location ?g - gripper)
		:precondition (and  (ball ?b) (room ?r) (gripper ?g) (atrob ?r) (carry ?b ?g) (turndomain))
		:effect (oneof (d2 (and (at ?b ?r) (free ?g) (not (carry ?b ?g)) (not (turndomain))))
		 (d1 (and (at ?b ?r) (not (free ?g)) (carry ?b ?g) (not (turndomain))))
		)
	)
	(:action trans-02 
		:parameters (?o14 - object ?r79 - location)
		:precondition (and  (or (and (q1 ?o14 ?r79) (not (at ?o14 ?r79)) (not (atrob ?r79))) (and (q1 ?o14 ?r79) (at ?o14 ?r79) (atrob ?r79)) (and (q2 ?o14 ?r79) (at ?o14 ?r79) (atrob ?r79)) ) (not (turndomain)))
		:effect (and (q1 ?o14 ?r79) (not (q2 ?o14 ?r79)) (turndomain))
	)
	(:action trans-12 
		:parameters (?o14 - object ?r79 - location)
		:precondition (and  (or (and (q1 ?o14 ?r79) (not (at ?o14 ?r79)) (atrob ?r79)) (and (q1 ?o14 ?r79) (at ?o14 ?r79) (not (atrob ?r79))) (and (q2 ?o14 ?r79) (not (at ?o14 ?r79))) (and (q2 ?o14 ?r79) (at ?o14 ?r79) (not (atrob ?r79))) ) (not (turndomain)))
		:effect (and (q2 ?o14 ?r79) (not (q1 ?o14 ?r79)) (turndomain))
	)
	(:action trans-01 
		:parameters (?loc68 - location ?o87 - object)
		:precondition (and  (or (and (q1 ?loc68 ?o87) (not (atrob ?loc68))) (and (q1 ?loc68 ?o87) (atrob ?loc68) (at ?o87 ?loc68)) (and (q2 ?loc68 ?o87) (at ?o87 ?loc68)) ) (not (turndomain)))
		:effect (and (q1 ?loc68 ?o87) (not (q2 ?loc68 ?o87)) (turndomain))
	)
	(:action trans-11 
		:parameters (?loc68 - location ?o87 - object)
		:precondition (and  (or (and (q1 ?loc68 ?o87) (atrob ?loc68) (not (at ?o87 ?loc68))) (and (q2 ?loc68 ?o87) (not (at ?o87 ?loc68))) ) (not (turndomain)))
		:effect (and (q2 ?loc68 ?o87) (not (q1 ?loc68 ?o87)) (turndomain))
	)
)
