(define (domain gripper)
	(:requirements :typing :strips :non-deterministic)
	(:types location gripper object)
	(:predicates (atrob ?loc - location) (spare-in ?loc - location) (adj ?from - location ?to - location) (room ?r - location) (ball ?o - object) (gripper ?gr - gripper) (at ?o - object ?r - location) (free ?gr - gripper) (carry ?o - object ?gr - gripper) (scratch) (turnDomain) (q2 ?o57 - object ?r84 - location) (q1 ?o57 - object ?r84 - location))
	(:action move
		:parameters (?from - location ?to - location)
		:precondition (and (atrob ?from) (adj ?from ?to) (room ?from) (turnDomain))
		:effect (and (not (atrob ?from)) (atrob ?to) (not (turnDomain)))
	)
	(:action pick
		:parameters (?b - object ?r - location ?g - gripper)
		:precondition (and (atrob ?r) (ball ?b) (gripper ?g) (at ?b ?r) (free ?g) (turnDomain))
		:effect (and (carry ?b ?g) (not (at ?b ?r)) (not (free ?g)) (not (turnDomain)))
	)
	(:action drop
		:parameters (?b - object ?r - location ?g - gripper)
		:precondition (and (ball ?b) (room ?r) (gripper ?g) (atrob ?r) (carry ?b ?g) (turnDomain))
		:effect (and (at ?b ?r) (free ?g) (not (carry ?b ?g)) (not (turnDomain)))
	)
	(:action trans-0
		:parameters (?o57 - object ?r84 - location)
		:precondition (and (or (and (q1 ?o57 ?r84) (at ?o57 ?r84) (atrob ?r84)) (q2 ?o57 ?r84)) (not (turnDomain)))
		:effect (and (q2 ?o57 ?r84) (not (q1 ?o57 ?r84)) (turnDomain))
	)
	(:action trans-1
		:parameters (?o57 - object ?r84 - location)
		:precondition (and (or (and (q1 ?o57 ?r84) (not (at ?o57 ?r84))) (and (q1 ?o57 ?r84) (at ?o57 ?r84) (not (atrob ?r84)))) (not (turnDomain)))
		:effect (and (q1 ?o57 ?r84) (not (q2 ?o57 ?r84)) (turnDomain))
	)
)