(define (problem problem1)
	(:domain gripper)
	(:objects r1 r2 - location g - gripper b1 b2 - object)
	(:init (adj r1 r2) (at b1 r1) (at b2 r1) (atrob r1) (ball b1) (ball b2) (free g) (gripper g) (q1 b1 r2) (room r1) (room r2) (turnDomain))
(:goal (and (q1 b1 r2) (turnDomain)))
)