(define (domain gripper)
	(:requirements :typing :strips :non-deterministic)
	(:types location gripper object)
	(:predicates (atrob ?loc - location) (spare-in ?loc - location) (adj ?from - location ?to - location) (room ?r - location) (ball ?o - object) (gripper ?gr - gripper) (at ?o - object ?r - location) (free ?gr - gripper) (carry ?o - object ?gr - gripper) (scratch) (turnDomain) (q1 ?loc68 - location ?o87 - object) (q2 ?loc68 - location ?o87 - object))
	(:action move
		:parameters (?from - location ?to - location)
		:precondition (and (atrob ?from) (adj ?from ?to) (room ?from) (turnDomain))
		:effect (and (not (atrob ?from)) (atrob ?to) (scratch) (not (turnDomain)))
	)
	(:action pick
		:parameters (?b - object ?r - location ?g - gripper)
		:precondition (and (atrob ?r) (ball ?b) (gripper ?g) (at ?b ?r) (free ?g) (turnDomain))
		:effect (and (at ?b ?r) (free ?g) (not (carry ?b ?g)) (not (turnDomain)))
	)
	(:action drop
		:parameters (?b - object ?r - location ?g - gripper)
		:precondition (and (ball ?b) (room ?r) (gripper ?g) (atrob ?r) (carry ?b ?g) (turnDomain))
		:effect (and (at ?b ?r) (not (free ?g)) (carry ?b ?g) (not (turnDomain)))
	)
	(:action trans-0
		:parameters (?loc68 - location ?o87 - object)
		:precondition (and (or (and (q1 ?loc68 ?o87) (not (atrob ?loc68))) (and (q1 ?loc68 ?o87) (atrob ?loc68) (at ?o87 ?loc68)) (and (q2 ?loc68 ?o87) (at ?o87 ?loc68))) (not (turnDomain)))
		:effect (and (q1 ?loc68 ?o87) (not (q2 ?loc68 ?o87)) (turnDomain))
	)
	(:action trans-1
		:parameters (?loc68 - location ?o87 - object)
		:precondition (and (or (and (q1 ?loc68 ?o87) (atrob ?loc68) (not (at ?o87 ?loc68))) (and (q2 ?loc68 ?o87) (not (at ?o87 ?loc68)))) (not (turnDomain)))
		:effect (and (q2 ?loc68 ?o87) (not (q1 ?loc68 ?o87)) (turnDomain))
	)
)